package com.example.learnopengl

object IMyNativeRendererType {
    const val RENDER_TYPE: String = "RENDER_TYPE"
    const val SAMPLE_TYPE = 100.0F


    const val SAMPLE_TYPE_VAO_VBO = SAMPLE_TYPE + 1.0f
    const val SAMPLE_TYPE_EBO = SAMPLE_TYPE + 2.0f
    const val SAMPLE_TYPE_VAO_VBO_EXERCISE_1 = SAMPLE_TYPE + 3.1f
    const val SAMPLE_TYPE_VAO_VBO_EXERCISE_2 = SAMPLE_TYPE + 3.2f
    const val SAMPLE_TYPE_UNIFORM = SAMPLE_TYPE + 4.0f
    const val SAMPLE_TYPE_TEXTURE_WARP = SAMPLE_TYPE + 5.1f
    const val SAMPLE_TYPE_TEXTURE_UNIT = SAMPLE_TYPE + 5.2f
    const val SAMPLE_TYPE_TEXTURE_EXERCISE_1 = SAMPLE_TYPE + 5.3f
    const val SAMPLE_TYPE_TEXTURE_EXERCISE_2 = SAMPLE_TYPE + 5.4f
    const val SAMPLE_TYPE_TEXTURE_EXERCISE_3 = SAMPLE_TYPE + 5.5f
    const val SAMPLE_TYPE_TEXTURE_EXERCISE_4 = SAMPLE_TYPE + 5.6f
    const val SAMPLE_TYPE_MAT = SAMPLE_TYPE + 6.0f
    const val SAMPLE_TYPE_COORDINATE = SAMPLE_TYPE + 7.0f
    const val SAMPLE_TYPE_COORDINATE_EXERCISE_1 = SAMPLE_TYPE + 7.1f
    const val SAMPLE_TYPE_COORDINATE_EXERCISE_2 = SAMPLE_TYPE + 7.2f
    const val SAMPLE_TYPE_COORDINATE_EXERCISE_3 = SAMPLE_TYPE + 7.3f
    const val SAMPLE_TYPE_CAMERA = SAMPLE_TYPE + 8.0f
    const val SAMPLE_TYPE_CAMERA_AUTO_MOVE = SAMPLE_TYPE + 8.1f
    const val SAMPLE_TYPE_COLORS = SAMPLE_TYPE + 9.0f
    const val SAMPLE_TYPE_COLORS_VIEW_EXERCISE_1 = SAMPLE_TYPE + 9.1f
    const val SAMPLE_TYPE_COLORS_VIEW_EXERCISE_2 = SAMPLE_TYPE + 9.2f
    const val SAMPLE_TYPE_COLORS_VIEW_EXERCISE_3 = SAMPLE_TYPE + 9.3f
    const val SAMPLE_TYPE_COLORS_VIEW_EXERCISE_4 = SAMPLE_TYPE + 9.4f
    const val SAMPLE_TYPE_COLORS_VIEW = SAMPLE_TYPE + 10.0f
    const val SAMPLE_TYPE_COLORS_MATERIAL = SAMPLE_TYPE + 11.0f
    const val SAMPLE_TYPE_COLORS_MATERIAL_EXERCISE = SAMPLE_TYPE + 11.1f
    const val SAMPLE_TYPE_LIGHTING_MAPS_DIFFUSE = SAMPLE_TYPE + 12.0f
    const val SAMPLE_TYPE_LIGHTING_MAPS_SPECULAR = SAMPLE_TYPE + 12.1f
    const val SAMPLE_TYPE_LIGHTING_MAPS_EXERCISE_1 = SAMPLE_TYPE + 12.2f
    const val SAMPLE_TYPE_LIGHTING_MAPS_EXERCISE_2 = SAMPLE_TYPE + 12.3f
    const val SAMPLE_TYPE_LIGHTING_MAPS_EXERCISE_3 = SAMPLE_TYPE + 12.4f
    const val SAMPLE_TYPE_LIGHTING_MAPS_EXERCISE_4 = SAMPLE_TYPE + 12.5f
    const val SAMPLE_TYPE_LIGHTING_CASTERS_DIRECTIONAL = SAMPLE_TYPE + 13.0f
    const val SAMPLE_TYPE_LIGHTING_CASTERS_POINT = SAMPLE_TYPE + 13.1f
    const val SAMPLE_TYPE_LIGHTING_CASTERS_SPOT = SAMPLE_TYPE + 13.2f
    const val SAMPLE_TYPE_LIGHTING_MERGE = SAMPLE_TYPE + 14.0f
    const val SAMPLE_TYPE_MODEL_LOADING = SAMPLE_TYPE + 15.0f
    const val SAMPLE_TYPE_DEPTH_TESTING = SAMPLE_TYPE + 16.0f
    const val SAMPLE_TYPE_DEPTH_DISPLAY = SAMPLE_TYPE + 16.1f
    const val SAMPLE_TYPE_STENCIL_TESTING = SAMPLE_TYPE + 17.0f
    const val SAMPLE_TYPE_BLENDING_DISCARD = SAMPLE_TYPE + 18.0f
    const val SAMPLE_TYPE_CULL_FACE = SAMPLE_TYPE + 19.0f
    const val SAMPLE_TYPE_FRAME_BUFFERS = SAMPLE_TYPE + 20.0f
    const val SAMPLE_TYPE_FRAME_BUFFERS_EXERCISE = SAMPLE_TYPE + 20.1f
    const val SAMPLE_TYPE_CUBE_MAPS = SAMPLE_TYPE + 21.0f
    const val SAMPLE_TYPE_CUBE_MAPS_REFLECTION1 = SAMPLE_TYPE + 21.1f
    const val SAMPLE_TYPE_CUBE_MAPS_REFLECTION2 = SAMPLE_TYPE + 21.2f
    const val SAMPLE_TYPE_CUBE_MAPS_REFRACTION = SAMPLE_TYPE + 21.3f
    const val SAMPLE_TYPE_CUBE_MAPS_EXERCISE = SAMPLE_TYPE + 21.4f
    const val SAMPLE_TYPE_ADVANCED_GLSL_POINT_SIZE = SAMPLE_TYPE + 22.0f
    const val SAMPLE_TYPE_ADVANCED_GLSL_FRAGCOORD = SAMPLE_TYPE + 22.1f
    const val SAMPLE_TYPE_ADVANCED_GLSL_FRONT_FACING = SAMPLE_TYPE + 22.2f
    const val SAMPLE_TYPE_ADVANCED_GLSL_FRAG_DEPTH = SAMPLE_TYPE + 22.3f
    const val SAMPLE_TYPE_CUBE_UNIFORM_BUFFER = SAMPLE_TYPE + 22.5f
    const val SAMPLE_TYPE_GEOMETRY_SHADER = SAMPLE_TYPE + 23.0f
    const val SAMPLE_TYPE_GEOMETRY_SHADER_TRIANGLE_STRIP = SAMPLE_TYPE + 23.1f
    const val SAMPLE_TYPE_GEOMETRY_SHADER_EXPLODE = SAMPLE_TYPE + 23.2f
    const val SAMPLE_TYPE_GEOMETRY_SHADER_NORMAL = SAMPLE_TYPE + 23.3f
    const val SAMPLE_TYPE_INSTANCING = SAMPLE_TYPE + 24.0f
    const val SAMPLE_TYPE_INSTANCING_ASTEROIDS = SAMPLE_TYPE + 24.1f
    const val SAMPLE_TYPE_ANIT_ALIASING = SAMPLE_TYPE + 25.0f
    const val SAMPLE_TYPE_ADVANCED_LIGHTING = SAMPLE_TYPE + 26.0f
    const val SAMPLE_TYPE_ADVANCED_LIGHTING_GAMMA_CORRECTED = SAMPLE_TYPE + 27.0f
    const val SAMPLE_TYPE_SHADOW_MAPPING_DEPTH = SAMPLE_TYPE + 28.0f
    const val SAMPLE_TYPE_SHADOW_MAPPING_BASE = SAMPLE_TYPE + 29.0f
    const val SAMPLE_TYPE_NORMAL_MAPPING = SAMPLE_TYPE + 30.0f
    const val SAMPLE_TYPE_PARALLAX_MAPPING = SAMPLE_TYPE + 31.0f
    const val SAMPLE_TYPE_STEEP_PARALLAX_MAPPING = SAMPLE_TYPE + 32.0f
    const val SAMPLE_TYPE_PARALLAX_OCCLUSION_MAPPING = SAMPLE_TYPE + 33.0f
    const val SAMPLE_TYPE_HDR = SAMPLE_TYPE + 34.0f
    const val SAMPLE_TYPE_BLOOM = SAMPLE_TYPE + 35.0f
    const val SAMPLE_TYPE_DEFERRED_SHADING = SAMPLE_TYPE + 36.0f
    const val SAMPLE_TYPE_SSAO = SAMPLE_TYPE + 37.0f
    const val SAMPLE_TYPE_PBR_LIGHTING = SAMPLE_TYPE + 38.0f
    const val SAMPLE_TYPE_PBR_LIGHTING_TEXTURED = SAMPLE_TYPE + 39.0f
    const val SAMPLE_TYPE_PBR_IBL_IRRADIANCE_CONVERSION = SAMPLE_TYPE + 40.0f
    const val SAMPLE_TYPE_PBR_IBL_IRRADIANCE = SAMPLE_TYPE + 41.0f
    const val SAMPLE_TYPE_PBR_IBL_SPECULAR = SAMPLE_TYPE + 42.0f
    const val SAMPLE_TYPE_PBR_IBL_SPECULAR_TEXTURED = SAMPLE_TYPE + 43.0f
    const val SAMPLE_TYPE_TEXT_RENDERING = SAMPLE_TYPE + 44.0f
    const val SAMPLE_TYPE_DEBUGGING = SAMPLE_TYPE + 45.0f
    const val SAMPLE_TYPE_BREAK_OUT = SAMPLE_TYPE + 46.0f
    const val SAMPLE_TYPE_WEIGHTED_BLENDED_OIT = SAMPLE_TYPE + 47.0f

}

object Key {
    const val KEY_W = 1
    const val KEY_S = 2
    const val KEY_A = 3
    const val KEY_D = 4
    const val KEY_B = 5
}