package com.example.learnopengl

object IMyNativeRendererType {
    const val RENDER_TYPE: String = "RENDER_TYPE"
    const val SAMPLE_TYPE = 100

    const val SAMPLE_TYPE_TRIANGLE = SAMPLE_TYPE
    const val SAMPLE_TYPE_RECTANGLE = SAMPLE_TYPE + 1
    const val SAMPLE_TYPE_TRIANGLE2 = SAMPLE_TYPE + 2
    const val SAMPLE_TYPE_TRIANGLE3 = SAMPLE_TYPE + 3
    const val SAMPLE_TYPE_TRIANGLE4 = SAMPLE_TYPE + 4
    const val SAMPLE_TYPE_TRIANGLE5 = SAMPLE_TYPE + 5
    const val SAMPLE_TYPE_TEXTURE = SAMPLE_TYPE + 6
    const val SAMPLE_TYPE_TEXTURE2 = SAMPLE_TYPE + 7
    const val SAMPLE_TYPE_MAT = SAMPLE_TYPE + 8
    const val SAMPLE_TYPE_COORDINATE = SAMPLE_TYPE + 9
    const val SAMPLE_TYPE_CAMERA = SAMPLE_TYPE + 10
    const val SAMPLE_TYPE_CAMERA_AUTO_MOVE = SAMPLE_TYPE + 11
    const val SAMPLE_TYPE_COLORS = SAMPLE_TYPE + 12
    const val SAMPLE_TYPE_COLORS_VIEW = SAMPLE_TYPE + 13
    const val SAMPLE_TYPE_COLORS_MATERIAL = SAMPLE_TYPE + 14
    const val SAMPLE_TYPE_LIGHTING_MAPS_DIFFUSE = SAMPLE_TYPE + 15
    const val SAMPLE_TYPE_LIGHTING_CASTERS_DIRECTIONAL = SAMPLE_TYPE + 16
    const val SAMPLE_TYPE_LIGHTING_MERGE = SAMPLE_TYPE + 17
    const val SAMPLE_TYPE_MODEL_LOADING = SAMPLE_TYPE + 18
    const val SAMPLE_TYPE_DEPTH_TESTING = SAMPLE_TYPE + 19
    const val SAMPLE_TYPE_STENCIL_TESTING = SAMPLE_TYPE + 20
    const val SAMPLE_TYPE_BLENDING_DISCARD = SAMPLE_TYPE + 21
    const val SAMPLE_TYPE_CULL_FACE = SAMPLE_TYPE + 22
    const val SAMPLE_TYPE_FRAME_BUFFERS = SAMPLE_TYPE + 23
    const val SAMPLE_TYPE_FRAME_BUFFERS_EXERCISE = SAMPLE_TYPE + 24
    const val SAMPLE_TYPE_CUBE_MAPS = SAMPLE_TYPE + 25
    const val SAMPLE_TYPE_CUBE_MAPS_REFLECTION1 = SAMPLE_TYPE + 26
    const val SAMPLE_TYPE_CUBE_MAPS_REFLECTION2 = SAMPLE_TYPE + 27
    const val SAMPLE_TYPE_CUBE_MAPS_REFRACTION = SAMPLE_TYPE + 28
    const val SAMPLE_TYPE_CUBE_MAPS_EXERCISE = SAMPLE_TYPE + 29
    const val SAMPLE_TYPE_CUBE_UNIFORM_BUFFER = SAMPLE_TYPE + 30
    const val SAMPLE_TYPE_GEOMETRY_SHADER = SAMPLE_TYPE + 31
    const val SAMPLE_TYPE_INSTANCING = SAMPLE_TYPE + 32
    const val SAMPLE_TYPE_INSTANCING_ASTEROIDS = SAMPLE_TYPE + 33
    const val SAMPLE_TYPE_ANIT_ALIASING = SAMPLE_TYPE + 34
    const val SAMPLE_TYPE_ADVANCED_LIGHTING = SAMPLE_TYPE + 35
    const val SAMPLE_TYPE_ADVANCED_LIGHTING_GAMMA_CORRECTED = SAMPLE_TYPE + 36
}

object Key {
    const val KEY_W = 1
    const val KEY_S = 2
    const val KEY_A = 3
    const val KEY_D = 4
    const val KEY_B = 5
}